Fixing getSettings method to support domains & sites in the trusted_host_patterns array. Updating change log.
unleashedtech/dotenv-drupal pull request #2
Opened 2022-03-29 17:15 UTC by dl-unleashed-technologies

### Fixed

- Fixed construction of `trusted_host_patterns` array to support sites defined in the `SITES` constant.

2022-03-29 17:26 UTC, dshumakerUT requested changes
Looks good.  I'd recommend a comment with examples.  
`// This could result in patterns like 
[ 'www.domainAExample.com',   'subDomain.domainAExample.com', 'subDomainB.domainAExample.org' ] `

Much like the drupal settings.php has very verbose examples by default.  We want to ensure the users (developers) are getting the same feature set that they use to get when they used drupal defaults.  And also perhaps a little something about how this is better than that.  (Perhaps even linking to  https://www.drupal.org/docs/installing-drupal/trusted-host-settings )

2022-03-29 17:31 UTC, dshumakerUT commented
> Looks good. I'd recommend a comment with examples. `// This could result in patterns like [ 'www.domainAExample.com', 'subDomain.domainAExample.com', 'subDomainB.domainAExample.org' ] `
> 
> Much like the drupal settings.php has very verbose examples by default. We want to ensure the users (developers) are getting the same feature set that they use to get when they used drupal defaults. And also perhaps a little something about how this is better than that. (Perhaps even linking to https://www.drupal.org/docs/installing-drupal/trusted-host-settings )

Please also note that most developers will have to have an override of this of some sort to get their docksal, ddev, or DrupalVM to work properly and any suggestions you can add are greatly appreciated.

2022-03-29 17:33 UTC, dshumakerUT commented
> > Looks good. I'd recommend a comment with examples. `// This could result in patterns like [ 'www.domainAExample.com', 'subDomain.domainAExample.com', 'subDomainB.domainAExample.org' ] `
> > Much like the drupal settings.php has very verbose examples by default. We want to ensure the users (developers) are getting the same feature set that they use to get when they used drupal defaults. And also perhaps a little something about how this is better than that. (Perhaps even linking to https://www.drupal.org/docs/installing-drupal/trusted-host-settings )
> 
> Please also note that most developers will have to have an override of this of some sort to get their docksal, ddev, or DrupalVM to work properly and any suggestions you can add are greatly appreciated.

You could even go the Advanced ENV route if you wanted https://www.drupal.org/docs/installing-drupal/trusted-host-settings#s-advanced-instructions   (for local devs)

2022-03-29 23:27 UTC, danshumaker commented
Perfect thank you!

2022-03-30 16:10 UTC, dshumakerUT approved these changes
Great job!

2022-03-30 16:50 UTC, merged